on: [push]
name: Build .env file from secrets and vars
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

    - name: Extract environment name
      id: extract_environment
      env:
        ENVIRONMENT: ${{ steps.extract_branch.outputs.branch == 'main' && 'PRODUCTION' || 'STAGING' }}
      run: echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

    # Filter client secrets & vars and save .env file (names starting with [PRODUCTION|STAGING]_CLIENT or CLIENT_)
    - name: Save .env file
      run: |
        echo '''${{ toJSON(secrets || '') }}''' '''${{ toJSON(vars || '') }}''' | jq -r 'to_entries | map(select(.key | test("^(${{ steps.extract_environment.outputs.environment }}_CLIENT_|CLIENT_)"))) | map(.key + "=" + .value) | .[]' | sed -r 's/^(${{ steps.extract_environment.outputs.environment }}_CLIENT_|CLIENT_)//' > .env
        cat .env
