on: [push]
name: Export variables to output and environment and log
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: secrets
      run: |
        echo '${{ toJSON(secrets) }}' > tmp.txt
        jq -c tmp.txt 'keys'
    - name: vars
      run: |
        echo '${{ toJSON(vars) }}' > tmp.txt
  
