on: [push]
name: Export variables to output and environment and log
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: secrets
      run: |
        "${{ toJSON(secrets) }}" | jq 'keys'
    - name: vars
      run: |
        echo ${{ toJSON(vars) }}
  
